os: linux
dist: bionic
language: java
jdk: openjdk11
cache:
  directories:
    - "$HOME/.m2"
addons:
  sonarcloud:
    organization: molgenis
    token:
      secure: apB6zHzeY0/ZatWEiUohwX9A8aRM7JuLxnzuYZqVu/GZ97ZwG9BFEEzTQ44UF3vfPHSzg4IweE/gVO9z29vZqDHhYugwDmCMB8IMzADQTtixRJOzm6PZvOZduVW5ueTAJdEm28q7nLqjNZLLo7tuCKKb/XMhOSubUAh+M02/Tat6cdqbUGQyAb4yMv6oTP8RPsSnyVcaXEOtdevb0uiKl/vVR/B8Dcl1MLigV5aIAtYYcDmO8WvLs9m7Ka+xQTO5gAd9SJ8nI7131OXtIcvOpUQjd93IMI8bTpwrluXJzoTOL3nS0Ajf32pn223Ci28ZzCwEw4tsIwGWkYrk5Z6rqLPMV8qPgXfO0qETrUC9IxFuZGfGPv10wi9mgrvmOP3FdEkboQsw94aCN0JPMGfeP8cDGNYbwn4kylQchRa4gk50KXrfF6uLgK9q+lGYD8gHHSRKis8Ck+AbBCI6R2O1auoxt2mA1KGGzmVXzUOqtpFe/TbjWnHoHnXzftzR+mXC5ozziv6b9DUvKOU4MT+nyzwsMT8nofuzfsgILCms0iDV4RJYscBmSEENs/TA6PV8CuKmVVwv5+u4bJJjBknMZMI6V5UuiEu8I39rcelCfh0LAyNfCfgHdoZE5Mqovc48l0UuNEvkNkN9KIn2JysK0BspvuPdB+iUfQvPcMa78ug=
script:
  - mvn clean install sonar:sonar -Pcoverage -Dsonar.projectKey=molgenis_mvl-vcf-converter
deploy:
  provider: releases
  api_key:
    secure: flAkb1fMyrE6zk0GnFXIo3RYYn9OC2QdvJXfSPzX0RoyuXMY/xvRuNJbH+KRsR03H9exo6H+Gi+iFWxWTFxjpoq3lInlYTMu4JRaxOcsgab3NEXE6qa9lBCv9F0VSVqGbNgND/ndzdZ34db3s2a4vIEc9rGH9ek0lAxVM5liEfhn+gl6k4ld7al+PWDyVYyQ8sNDUgdUQieAOuXhkaXph11alJTw74TskUQ1qg1279ONoRFfTdu19gyHOeTD8eUS9A1MLr4HlEqZas5bNtS/nonK/7/j5+cbkGlBVWiwkvc4p5sCBEBmYvuHw0hjfkTF/S9y9ZAbyDtdwRw0ZeXfoJDM16k8P/A9YUR8MPPcTmU+yqobq57bt86zW/qUfiMPfpGnUj5dKJeLQJ/uoSSVg/eQjX1z9SoN1tsjJXV4H2oStTyshcrYpbSJrGEgbuYUYbDMmIQEa+wB/G0J2JHwfOat59PVw6fjgOL4k+j82m3h3xPFcJm5PF6V1g3PRACVipCknAq/OwhjUtGutTPAiDyhk5/QmNdc+MvpN2UeDXgd3FbKygMjAknZaEH/lEF1kgEJyVJDpyIGfdhh/NeIVP4+XMDeu+MCry4PNgkPzKrJCHCA1K7e9ybo78N/n1k7yUdKveiykBgtDB88FQVYA+6EzVfEXW4kC2OFzIlJb4w=
  file: target/mvl-vcf-converter.jar
  prerelease: true
  on:
    tags: true
  edge: true # opt in to dpl v2
